version: "3.9"
services:
  backend:
    container_name: backend
    command: "dev"
    build:
      context: .
    depends_on:
      - mongo
    networks:
      - mongo-net
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./app:/var/www/http/app
    environment:
      PORT: ${PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      USERNAME: ${MONGO_USER}
      PASSWORD: ${MONGO_PASSWORD}
      DATABASE: ${MONGO_DB}
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - mongo-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
networks:
  mongo-net:
