version: "3.9"
services:
  backend:
    container_name: backend
    command: "dev"
    build:
      context: .
    depends_on:
      - mongo
    networks:
      - mongo-net
    ports:
      - 3000:3000
    volumes:
      - ./app:/var/www/http/app
    environment:
      PORT: 3000
      FRONTEND_URL: "http://localhost:5173"
      USERNAME: root
      PASSWORD: example
      DATABASE: fake-artist
    restart: always
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    networks:
      - mongo-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: fake-artist
networks:
  mongo-net:
